  client{ID}:
    container_name: client{ID}
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID={ID}
      - INFO_NAME={INFO_NAME}
      - INFO_SURNAME={INFO_SURNAME}
      - INFO_DNI={INFO_DNI}
      - INFO_BIRTH={INFO_BIRTH}
      - INFO_NUMBER={INFO_NUMBER}
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - {CONFIG_FILE}:/usr/config.yaml
      - {AGENCY_FILE}:/usr/bets.csv
