  client{ID}:
    container_name: client{ID}
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID={ID}
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - {CONFIG_FILE}:/usr/config.yaml
