name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - /home/snmaror/Documents/distribuidos/tp0/server/config.ini:/usr/config.ini

